### ISSUE TITLE
alert is not Material 3 style on Android

### ISSUE THREAD

**Issue by BugsOverBugs** [zonble/flutter_platform_alert#14]
Hey, your package is awesome, but unfortunately the alert does not support the Material 3 dialog on Android 12 or higher. Can you implement it soon?

Other questions: 
1. Is there a way to disable destructive actions for MacOS?
2. Is there a way to customise the iOS alert dialog button styles (default / cancel / destructive) like [native_ios_dialog](https://pub.dev/packages/native_ios_dialog))? Because in other languages than English the automatic assignment does not work.
3.  Can you support light mode for Android dialogs?

**Comment by BugsOverBugs** [comment]
Thanks for your response.

I updated my pubspec like this
```yaml
flutter_platform_alert:
    git:
      url: https://github.com/zonble/flutter_platform_alert.git
      ref: material_android
```
cleaned the project and re-ran the build.

Now the dialog still looks like the old one but does not show the negative action.

Did I something wrong?
